// <auto-generated />
using System;
using BreakingScoreBoard.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BreakingScoreBoard.Api.Migrations
{
    [DbContext(typeof(BattleDbContext))]
    [Migration("20260131171309_AddDisplayNameToBreaker")]
    partial class AddDisplayNameToBreaker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.AgeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BracketSize")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxBirthYear")
                        .HasColumnType("integer");

                    b.Property<int?>("MinBirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_AgeCategories_EventId");

                    b.HasIndex("EventId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_AgeCategories_EventId_Name");

                    b.ToTable("AgeCategories", (string)null);
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BracketLevel")
                        .HasColumnType("integer");

                    b.Property<int>("BracketPosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("Breaker1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Breaker2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReBattle")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OriginalBattleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Breaker1Id");

                    b.HasIndex("Breaker2Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Battles_CategoryId");

                    b.HasIndex("OriginalBattleId");

                    b.HasIndex("WinnerId");

                    b.HasIndex("CategoryId", "BracketLevel")
                        .HasDatabaseName("IX_Battles_CategoryId_BracketLevel");

                    b.ToTable("Battles", (string)null);
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.BattleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminPinHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<int>("JudgeCount")
                        .HasColumnType("integer");

                    b.Property<string>("JudgePinHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("RegistrationOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BattleEvents", (string)null);
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.Breaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Breakers", (string)null);
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.JudgeScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BreakerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("JudgeIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BattleId")
                        .HasDatabaseName("IX_JudgeScores_BattleId");

                    b.HasIndex("BreakerId");

                    b.HasIndex("BattleId", "JudgeIdentifier", "BreakerId")
                        .HasDatabaseName("IX_JudgeScores_BattleId_JudgeIdentifier_BreakerId");

                    b.ToTable("JudgeScores", (string)null);
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BreakerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Registrations_CategoryId");

                    b.HasIndex("BreakerId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_Registrations_BreakerId_CategoryId");

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.AgeCategory", b =>
                {
                    b.HasOne("BreakingScoreBoard.Domain.Entities.BattleEvent", "Event")
                        .WithMany("Categories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.Battle", b =>
                {
                    b.HasOne("BreakingScoreBoard.Domain.Entities.Breaker", "Breaker1")
                        .WithMany()
                        .HasForeignKey("Breaker1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BreakingScoreBoard.Domain.Entities.Breaker", "Breaker2")
                        .WithMany()
                        .HasForeignKey("Breaker2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BreakingScoreBoard.Domain.Entities.AgeCategory", "Category")
                        .WithMany("Battles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BreakingScoreBoard.Domain.Entities.Battle", "OriginalBattle")
                        .WithMany()
                        .HasForeignKey("OriginalBattleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BreakingScoreBoard.Domain.Entities.Breaker", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Breaker1");

                    b.Navigation("Breaker2");

                    b.Navigation("Category");

                    b.Navigation("OriginalBattle");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.JudgeScore", b =>
                {
                    b.HasOne("BreakingScoreBoard.Domain.Entities.Battle", "Battle")
                        .WithMany("Scores")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BreakingScoreBoard.Domain.Entities.Breaker", "Breaker")
                        .WithMany()
                        .HasForeignKey("BreakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("Breaker");
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.Registration", b =>
                {
                    b.HasOne("BreakingScoreBoard.Domain.Entities.Breaker", "Breaker")
                        .WithMany("Registrations")
                        .HasForeignKey("BreakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BreakingScoreBoard.Domain.Entities.AgeCategory", "Category")
                        .WithMany("Registrations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breaker");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.AgeCategory", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.Battle", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.BattleEvent", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("BreakingScoreBoard.Domain.Entities.Breaker", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
